// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;
import service1.service2client;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The average score across the catalog Service2 currently serves
    #
    # + return - The computed average score
    resource function get average() returns AverageScore|http:InternalServerError {
        service2client:Catalog|error catalogResult = fetchCatalog();
        if catalogResult is error {
            log:printError("failed to fetch catalog from service2", 'error = catalogResult);
            ServiceError errorBody = {code: 500, message: "failed to fetch catalog from service2"};
            return <http:InternalServerError>{body: errorBody};
        }
        service2client:Record[] records = catalogResult.records;
        int recordCount = records.length();
        log:printInfo("handled records for average computation", recordCount = recordCount);
        // An empty catalog is a valid upstream state, not an application
        // error — the contract documents only this one successful response.
        if recordCount == 0 {
            return {average: 0};
        }
        int sum = 0;
        foreach service2client:Record rec in records {
            sum += rec.score;
        }
        // Integer division truncates toward zero.
        int average = sum / recordCount;
        return {average: average};
    }

    # Catch-all for any path/method this service does not serve.
    #
    # + return - A structured 404 body
    resource function 'default [string... path]() returns http:NotFound {
        ServiceError errorBody = {code: 404, message: "Not Found", description: "service1 does not serve this path"};
        return <http:NotFound>{body: errorBody};
    }
}

public type AverageScore record {
    # Sum of the catalog's record scores divided by the record count, truncated to a whole number
    int average;
};

public type ServiceError record {|
    int code;
    string message;
    string description?;
    string moreInfo?;
|};
