// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The catalog Service2 currently serves
    #
    # + return - The current catalog and its records
    resource function get catalog() returns Catalog {
        return currentCatalog();
    }

    # Switch between full and empty catalog mode (internal only, never reachable by a user)
    #
    # + return - returns can be any of following types
    # http:Ok (The mode was updated; the resulting catalog)
    # http:BadRequest (The requested mode is not valid)
    resource function put operations/mode(@http:Payload ModeChange payload) returns Catalog|ErrorBadRequest {
        return applyModeChange(payload.mode);
    }
}

public type ModeChange record {
    # The mode to switch to
    string mode;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Record record {
    # Record identifier
    int id;
    # Record name
    string name;
    # Record score
    int score;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Catalog record {
    # The catalog's current serving mode
    "full"|"empty" mode;
    # The records this catalog currently holds
    Record[] records;
};
